services:
  nifi:
    image: apache/nifi:2.0.0-M2
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: s3cr3t1
    ports:
      - 8443:8443
    volumes:
      - ./nifi-ext:/opt/nifi/nifi-current/nar_extensions:rw